// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frdsxqhqhelcbayjjtjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZHN4cWhxaGVsY2JheWpqdGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjIwNjQsImV4cCI6MjA2NjAzODA2NH0.WtbK3gjcVvU3JgihaT4KjyQkIXh5MTqbj4FlftA-1e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);